name: DesignCredit
description: "A new Flutter project."
publish_to: 'none'  
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  http: ^1.2.1
  shared_preferences: ^2.2.2
  tuple: ^2.0.2
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.2.5
  file_picker: ^6.2.0
  path: ^1.9.0
  dio: ^5.4.1
  mime: ^1.0.5
  http_parser: ^4.0.2
  firebase_messaging: ^14.7.20
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  # flutter_launcher_icons: ^0.13.1
  # file_picker_web: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21  
  web:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    icon_size: 48  
  macos:
    generate: true
    image_path: "assets/images/ic_launcher.png"





  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
