// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDjt4S66A528F-d_2nDu7t4ffbrqqFQOQo",
    authDomain: "softwareproject-100ba.firebaseapp.com",
    projectId: "softwareproject-100ba",
    storageBucket: "softwareproject-100ba.appspot.com",
    messagingSenderId: "1081628182897",
    appId: "1:1081628182897:web:0345e76b511b27b7dfced0",
    measurementId: "G-4C3BPPBPTW",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjt4S66A528F-d_2nDu7t4ffbrqqFQOQo',
    appId: '1:1081628182897:android:daf21c568588e90fdfced0',
    messagingSenderId: '1081628182897',
    projectId: 'softwareproject-100ba',
    storageBucket: 'softwareproject-100ba.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyC4gI9OMFtU8hu4sqvIpf6PX7SnEbxbGLA',
  //   appId: '1:598948981790:ios:ef3d576d701e732003920f',
  //   messagingSenderId: '598948981790',
  //   projectId: 'prometeo24',
  //   storageBucket: 'prometeo24.appspot.com',
  //   iosBundleId: 'com.example.frontend',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyC4gI9OMFtU8hu4sqvIpf6PX7SnEbxbGLA',
  //   appId: '1:598948981790:ios:063754248a4f6efd03920f',
  //   messagingSenderId: '598948981790',
  //   projectId: 'prometeo24',
  //   storageBucket: 'prometeo24.appspot.com',
  //   iosBundleId: 'com.example.frontend.RunnerTests',
  // );
}
